name: gestec
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  go_router: ^15.1.2
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  font_awesome_flutter: ^10.8.0
  flutter_dotenv: ^5.2.1
  provider: ^6.1.5
  firebase_auth: ^5.5.4
  intl: ^0.19.0

  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
      - .env
      - assets/
      - assets/images/